name: smartshop_app
description: SmartShop - sales & inventory app
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.1.0
  provider: ^6.0.5
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
